server:
  port: 8080

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/words?currentSchema=public
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

words:
  path: src/main/java/com/ogul/wordfinder/entity/words/words.txt

